[project]
name = 'agritech-verifier'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.data-validator]
path = 'contracts/data-validator.clar'
clarity_version = 3
epoch = 3.1

[contracts.equipment-registry]
path = 'contracts/equipment-registry.clar'
clarity_version = 3
epoch = 3.1

[contracts.field-station-registry]
path = 'contracts/field-station-registry.clar'
clarity_version = 3
epoch = 3.1

[contracts.precision-tools]
path = 'contracts/precision-tools.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
